### PR TITLE
Reuse code from make_art file in website/print file

### PR DESCRIPTION
**Pull request by Jesusz0r**
Remove duplicated code and reuse original code from make_art.py file inside /website/print.py file

### CODE REVIEW

**Comment by hvijaycse** [comment]
Hi there, @Jesusz0r 
Sorry, but the changes that you made to the program will stop crash the webpage, as this a standalone program you check it out on this [link](http://13.127.254.208/cgi-bin/pythonascii/print). There is no above directory for this program on the server and even if it was there and still it won't work as you removed some of the cgi code. Maintainer please don't accept this pr.

**Comment by Jesusz0r** [comment]
> Hi there, @Jesusz0r
> Sorry, but the changes that you made to the program will stop crash the webpage, as this a standalone program you check it out on this [link](http://13.127.254.208/cgi-bin/pythonascii/print). There is no above directory for this program on the server and even if it was there and still it won't work as you removed some of the cgi code. Maintainer please don't accept this pr.

Oh ok. Sorry.
How can I test the server? and where did I remove cgi code?

Thanks!

**Comment by hvijaycse** [comment]
You can test this program on Apache server, install Apache and place the program where your server support cgi files, this directory change according to os for redhat is /var/www/cgi and give permission for execution to the program, start the server and visit the link 127.0.0.1/cgi/print.py on the system browser itself, and i am sorry you didn't delete ay cgi code , GitHub showed me some line collapsed in one another and i thought you deleted them, sorry for this.

**Comment by M-AlNoaimi** [comment]
@Jesusz0r I would encourage you to fix the bugs stated above, once you do we can approve this PR.

**Pull request closed without merging**
